# Generated by Django 4.2.1 on 2023-05-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='state',
            field=models.CharField(default='SC', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_line2',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
