# Generated by Django 4.2.1 on 2023-05-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.URLField(blank=True),
        ),
    ]
