# Generated by Django 4.2.1 on 2023-05-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_img1_product_img2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductOptions',
            new_name='ProductOption',
        ),
    ]
