# Generated by Django 4.2.1 on 2023-05-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_productoptions_productoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_line2',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
