# Generated by Django 4.2.1 on 2023-05-07 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_product_inventory_id_option_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.productdiscount'),
        ),
    ]
