# Generated by Django 4.2.1 on 2023-05-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_product_discount_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
