# Generated by Django 4.2.1 on 2023-05-13 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_useraddress_recipient_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
    ]
