# Generated by Django 4.2.1 on 2023-05-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_orderdetails_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='recipient_name',
            field=models.CharField(default='SC', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='state',
            field=models.CharField(default='SC', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='tracking_no',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
