# Generated by Django 4.2.1 on 2023-05-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_orderitems_orderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentDetails',
            new_name='PaymentDetail',
        ),
    ]
