# Generated by Django 4.2.1 on 2023-05-13 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_paymentdetails_paymentdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='session_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='api.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShoppingSession',
        ),
    ]
